### ISSUE TITLE
"onDragStart" method not prevent drag action when return false 

### ISSUE THREAD

**Issue by Elango7** [jtiscione/chessboard3js#2]
Hi sir onDragStart method not prevent drag action when return false.

 var cfg = {
            cameraControls: false,
            draggable: true,
            position: 'start',
            onDrop: onDrop,
            onMouseoutSquare: onMouseoutSquare,
            onMouseoverSquare: onMouseoverSquare,
            onSnapEnd: onSnapEnd,
             rotateControls : false,
            onDragStart: onDragStart,
            lightSquareColor : 0xffffff,
           darkSquareColor : 0x000000,
           pieceSet : 'assets/chesspieces/classic/{piece}.json',
            backgroundColor : 0x0b1038
        };

    var onDragStart = function(source, piece, position, orientation) {
 if ((orientation === 'white' && piece.search(/^w/) === -1) ||
      (orientation === 'black' && piece.search(/^b/) === -1)) {
    return false;
  }
 
};

board = new ChessBoard3('board', cfg);

**Comment by jtiscione** [comment]
Fixed in 0.1.2. (Line 1488 was missing.)
The chessboard now uses version 80 of three.js (prior three.js versions won't work). Dependencies on helvetiker_regular.js and tween.js have been removed.
