### ISSUE TITLE
Is there an option for rotating 2D board?

### ISSUE THREAD

**Issue by ngocdaothanh** [jtiscione/chessboard3js#6]
I'm creating a chess variant that requires rotating the chessboard 45 degrees.

Is there an option for rotating the board in 2D?
Or better, is there an option to (pre)set the rotation of the board to, for example, x=0 y=0 z=45, and won't let users to rotate the board?

**Comment by jtiscione** [comment]
I didn't write the 2D board; that one is chessboard.js. It's just using JQuery to populate a DIV element with some HTML of squares and pieces. It supports two positions: 0 and 180 degrees.
If you want to rotate it by an arbitrary angle I guess you could try applying this CSS to its div:
"transform: rotate(45deg); transform-origin: center;"
Hopefully that won't give you problems with the mouse.

**Comment by ngocdaothanh** [comment]
Thanks for the info.

I have a follow up question/feature request:
https://github.com/jtiscione/chessboard3js/issues/7
